server.port=8761
spring.application.name=eureka

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html