server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://MS-AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: ms-usuario
          uri: lb://MS-USUARIO
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - JwtAuthenticationFilter
        - id: ms-mascotas
          uri: lb://MS-MASCOTAS
          predicates:
            - Path=/api/v1/mascotas/**
          filters:
            - JwtAuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
