server.port=${SERVER_PORT:8081}
spring.application.name=ms-auth

jwt.secret=${JWT_SECRET:MiClaveSuperSecretaYMuyLargaParaDesarrolloLocal123456789}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
usuarios.service.url=${USUARIOS_SERVICE_URL:http://localhost:8082/api/v1/usuarios}
