server.port=8084

spring.application.name=ms-veterinaria

spring.datasource.url=jdbc:postgresql://localhost:5432/db_veterinaria
spring.datasource.username=postgres
spring.datasource.password=admin12
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente en Postgres si no existen
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que Spring hace por debajo (súper útil para el profe)
spring.jpa.show-sql=true

# Le dice a Hibernate cómo hablar el "idioma" específico de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect