spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: ms-usuario
  profiles:
    active: dev
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
