server.port=${SERVER_PORT:8082}
spring.application.name=ms-usuario

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ms_usuario_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
